### ISSUE TITLE
config diff is hard to read in dark mode

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#26]
the config diff in dark mode has a unreadable color scheme.

**Describe the solution you'd like**
a color scheme that is usable in dark mode

**Describe alternatives you've considered**
toggle to light mode when reading the config diff

**Comment by miaow2** [comment]
Hi @chris240189 , thank you for opening this issue.

I've just pushed the beta version of the new release to PyPi with a dark theme for diff.
You can try it by updating plugin with pip
`pip install netbox-config-diff==1.2.1b1`
After that collect static for NetBox
`python manage.py collectstatic --noinput`
and restart NetBox.

This is how it looks 
![image](https://github.com/miaow2/netbox-config-diff/assets/28296817/4d9c1724-b77c-42fd-868a-9eb01c1fb881)

**Comment by miaow2** [comment]
Fix in release [1.2.1](https://github.com/miaow2/netbox-config-diff/releases/tag/1.2.1)

**Comment by chris240189** [comment]
awesome!
