### ISSUE TITLE
Device selection

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#37]
**Is your feature request related to a problem? Please describe.**
The selection of devices for the config diff generation by the script is somewhat cumbersome for me as I have about 20 devices spread across 10+ sites.  Which means lots of clicks in the GUI when I want to reschedule the custom script.

**Describe the solution you'd like**
I'd like to use the device role for selecting devices.

**Describe alternatives you've considered**
So far I have been manually selecting each device by clicking on it.

**Comment by miaow2** [comment]
Hi @chris240189 thanks for opening issue, I will add to the script device role field
