### ISSUE TITLE
Device template bound to model/platform instead of device instance.

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#38]
**Is your feature request related to a problem? Please describe.**
When I updated to 2.x I haven't been able to select devices anymore. I found out, that the device template  is now mandatory on the device?
Whats the reason for this change? I thought getting at least some basic template inherited from the platform to be a good default.

**Comment by miaow2** [comment]
Hi @chris240189, I did not get, where you can't select devices? in ConfigDiffScript?

**Comment by miaow2** [comment]
@chris240189 I get it, I will delete the requirement that devices need assigned config templates
