### ISSUE TITLE
mandatory device "active" status

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#39]
**Is your feature request related to a problem? Please describe.**
I do have two different groups of devices to manage: devices in production and devices in a lab setup for testing.
So far I had set all production devices to status _active_ and devices in the lab as _staging_ which means for the latter I cannot generate any diffs.

**Describe the solution you'd like**
Not being as strict and allowing devices with other status to be allowed in the device selection.

**Describe alternatives you've considered**
Maybe I am using the _staging_ status wrong. I am unsure, what the general consensus is here about keeping multiple sets of devices _online_ that allows for configuration, testing, etc, while still keeping production and testing separate. Maybe the answer is tags, but I find tags cumbersome to work with through the API.

**Comment by miaow2** [comment]
Hi @chris240189 thanks for opening issue, I will add to the script status field
