### ISSUE TITLE
Make the ConfigDiffScript spam the change log less

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#43]
**Is your feature request related to a problem? Please describe.**
Running the ConfigDiffScript on a schedule creates one change log entry (/extras/changelog/) for each device and run of the script not considering if there was a change in the diff or not.

**Describe the solution you'd like**
If the result (meaning the content of diff) stays the same, do not create a log entry.

Is the changelog on the dashboard filterable in any way?

**Comment by miaow2** [comment]
Hi @chris240189 you can press gear button on the changelog dashboard and in `URL parameters` add query params, I think there you can filter output
