### ISSUE TITLE
Move Menu item to dedicated section

### ISSUE THREAD

**Issue by PieterL75** [miaow2/netbox-config-diff#47]
The 'Netbox Config Diff Plugin' is now located under the 'Plugins' Section of the main menu
You can create your own section to move the plugin into. 
That would make the accessibiliy of the plugin much easier
https://docs.netbox.dev/en/stable/plugins/development/navigation/#menus

**Comment by chris240189** [comment]
to add to this, having the config compliance object as a tab in the device (next to the rendered config for example)
