### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#53]
**NetBox version**
What version of NetBox are you currently running? 
3.6.6

**Describe the bug**
Upon a fresh installation and following the installation manual, the config diff script job gets stuck as running.

after restarting netbox with 
`sudo systemctl restart netbox netbox-rq`
(note the additional netbox-rw), the script works as expected.

**Comment by miaow2** [comment]
hi @chris240189 thanks for opening the issue
It's my mistake to miss `netbox-rq` on docs, I will add this
