### ISSUE TITLE
Add support for NetBox 4.0

### ISSUE THREAD

**Issue by miaow2** [miaow2/netbox-config-diff#62]

**Comment by lc787** [comment]
Hey, any updates on 4.0 support? (no rush, of course)

**Comment by miaow2** [comment]
@lc787 Hi, update in process, but before it, I should fix some little bugs

**Comment by salvador-andes** [comment]
Hi @miaow2 I hope you're doing well, I was wondering if you had the chance to fix the bugs, we would love this plugin in Netbox v4 :D

**Comment by miaow2** [comment]
Hi @salvador-andes yes, I've fixed the bags, this weekends I will return to adding support for 4 NetBox

**Comment by salvador-andes** [comment]
> Hi @salvador-andes yes, I've fixed the bags, this weekends I will return to adding support for 4 NetBox

Awesome! Thank you @miaow2
