### ISSUE TITLE
Add default_desired_privilege_level option

### ISSUE THREAD

**Issue by cknost** [miaow2/netbox-config-diff#67]
**Is your feature request related to a problem? Please describe.**
You need the enable password in the netbox config to enter privilege_exec mode.

**Describe the solution you'd like**
A new parameter named default_desired_privilege_level, which define a new default desired privilege level for scrapli.

**Additional context**
I will make a merge request.

**Comment by miaow2** [comment]
Hi @cknost, thanks for opening the issue and PR! I will take a look as soon as I will have free time.
