### ISSUE TITLE
Create some statistics about the diff.

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#76]
I am working towards getting a couple of switches fully automated and to get a feel of how "big" a diff is, it would be useful to not only having a status attribute, but also something like "102 insertions(+), 22 deletions(-)" exposed to be used as sortable columns in the config compliance overview or just the lines of code of the "patch" output.

**Comment by miaow2** [comment]
Hi @chris240189 thanks for your suggestion, I should think about how to implement this, but I'm unlikely to be able to do any sorting because my knowledge of JavaScript is very small

**Comment by chris240189** [comment]
we are going to right direction with the latest update, however, when I go to
<mynetbox>/plugins/config-diff/config-compliances/
I cannot add the diff-statistics as columns in the table.

![image](https://github.com/user-attachments/assets/037232ff-4841-4a98-b380-c9ccbd3166d3)

**Comment by miaow2** [comment]
I added statistics only to ConfigCompliance page 

![image](https://github.com/user-attachments/assets/14d7edb8-31b0-463a-bc1f-edac018b7134)

Where do you want to see it as well?

**Comment by chris240189** [comment]
When you go to <your netbox base url>/plugins/config-diff/config-compliances/
There is a big table view showing all the compliances in a table.
That table is customizable and I'd like to add the statistics as a column in that table (see my screenshot above, where the column is not selectable).
