### ISSUE TITLE
Add support for NetBox 4.1

### ISSUE THREAD

**Issue by miaow2** [miaow2/netbox-config-diff#79]

**Comment by chris240189** [comment]
I tried updating to v4.1 and ran into this error:
```
from dcim.api.serializers import NestedDeviceSerializer, NestedPlatformSerializer
ImportError: cannot import name 'NestedDeviceSerializer' from 'dcim.api.serializers' (/opt/netbox/netbox/dcim/api/serializers.py)
```
I tried updating to v4.1 without the plugin, then installing afterwards, the same issue.

I wonder how netbox-config-diff will integrate with the new netbox branching feature.

**Comment by miaow2** [comment]
Hi @chris240189, support for 4.1 NetBox is in progress,

About branching, in theory, it should work out of the box, because all plugins models use `ChangeLoggingMixin`, but I will check the compatibility with branching feature after adding support for 4.1
