### ISSUE TITLE
Regex in Substitute not working

### ISSUE THREAD

**Issue by jibz89** [miaow2/netbox-config-diff#81]
**NetBox version**
What version of NetBox are you currently running? 
v4.0.11

**Describe the bug**
plugin is not adding the substitute to template, it just adds the jinja2 variable name like {{ cisco_exclude_banner }}

**To Reproduce**
1. Go to 'Config Diff Plugin'
2. Click on 'Platform Settings'
3. Click on 'Add'
4. Click 'Platform' choose IOS (if you don't have platform go back to Device and create Platform)
5. For Driver type in cisco_iosxe
6. For Command 'show running-config'
7. Now Click on 'Create' to save Platform Settings
8. Next under Config Management Click on 'Substitutes'
9. Click 'Add'
10. Choose Platform settings create earlier (ex: IOS XE cisco_iosxe)
11. Name something like 'cisco_exclude_banner'
12. Regexp 'banner login [\S\s]+\^C'
13. Click 'Create' to save Substitute
14. Now Click on 'Provisioning' and then 'Config Templates'
15. Create Template type Name ex: test
16. Template Code enter the Substitute as jinja2 variable like {% raw %}{{ cisco_exclude_banner }}{% endraw %}
17. Click on Devices and Edit and Choose the Config template for device (Device must be Active status and have Primary IP and Platform IOS)
18. Now go back to Config Diff Plugin and Click 'Configuration Requests'
19. Click 'Add' Find the device and Click 'Create' to Save
20. Now click on 'Collect diffs'
21. No Error

**Expected behavior**
the matched config was not added into rendered output instead just the variable gets added {{ cisco_exclude_banner }}

**Screenshots**
![platforms](https://github.com/user-attachments/assets/496dcc53-87ae-46c4-92cd-010cd59c8d35)
![rendered diff pic 2](https://github.com/user-attachments/assets/032617b5-2008-47b5-879e-4c85aab78dfd)
![rendered diff](https://github.com/user-attachments/assets/56616d06-cbba-4346-8345-ec360ee9ceb2)
![sample_regex_test](https://github.com/user-attachments/assets/0b85382b-f71d-48e2-9388-02768bfa581c)
![sample_regex_test2](https://github.com/user-attachments/assets/aafcf609-cb7c-402b-b443-23c513a98b45)
![sample_regex_test3](https://github.com/user-attachments/assets/7c487fe9-4928-4cb6-b319-e9fc4ec43779)
![substitutes](https://github.com/user-attachments/assets/271ca2cc-80fd-457a-a24a-3e97ac1da66b)
![template](https://github.com/user-attachments/assets/2c971b6d-1cb6-4aa2-b7ad-ac2717cf4239)

**Additional context**
[sample_text_config.txt](https://github.com/user-attachments/files/17087835/sample_text_config.txt)

**Comment by miaow2** [comment]
Hi @jibz89, thanks for opening the issue.

I fix this bug in 2.7.0 version.

Please be caution with regex, because regex in `exclude_snmp_traps` matches `snmp-server` lines and lines after that section

**Comment by jibz89** [comment]
substitutes
 
![image](https://github.com/user-attachments/assets/0799967f-f010-4234-86aa-aeade7d2bfb5)

Rendered diff
 
![image](https://github.com/user-attachments/assets/96cb0a4e-e522-4f96-884d-5ed8fe9b29de)

Template
 
![image](https://github.com/user-attachments/assets/6040f7e2-6fbe-4b8f-b7a4-1d1056bf8e2e)


So I removed the snmp traps from the template but the banner substitutes is not still working (see screenshot). i also try creating another template with same code to exclude banner. i tested the regex in regex101. 
how can i get into the dev env of this plugin to see what its actually doing ?

**Comment by jibz89** [comment]
exclude_snmp_traps regex (snmp-server enable traps(?: .*$\n?)+)+ is only matching only lines starting with 'snmp-server enable traps'

**Comment by miaow2** [comment]
Hi @jibz89 , please share with me next data, so I can test plugin on your data, maybe I miss something and that's why can't catch the bug:

* actual config of the device (remove sensitive data)
* how rendered config in netbox looks like for the device (also remove sensitive data)
* what platform is assigned to the device
* substitutes data: name, regex and platform setting
* diff result from config compliance

> how can i get into the dev env of this plugin to see what its actually doing ?

in my env Netbox is installed how it is described in official docs.
then git clone plugins repo, activate netbox virtualvenv and go to the plugins directory and run `pip install -e .`

after that you will get locally installed version of the plugin, you can do change in it and see it

**Comment by jibz89** [comment]
-     actual config of the device (remove sensitive data)
[actual config of device.txt](https://github.com/user-attachments/files/17356757/actual.config.of.device.txt)

-     how rendered config in netbox looks like for the device (also remove sensitive data)
[rendered config in netbox.txt](https://github.com/user-attachments/files/17356759/rendered.config.in.netbox.txt)

-     what platform is assigned to the device
Device Platform settings are 
Platform: IOS XE 
Driver: cisco_iosxe 
Command: show running-config

-     substitutes data: name, regex and platform setting
Subtitutes Data:
Name: cisco_exclude_all_before_line
REGEXP: [.*\n\S\s]+\^C\n!
Platform Settings: IOS XE cisco_iosxe

cisco_exclude_all_except_line_and_space
REGEXP: ^(?!line\b)(?!\s).+$
Platform Settings: IOS XE cisco_iosxe

-     diff result from config compliance
I notice if I click on "Collect diffs" button in Configuration Requests in does not get the regex right and just prints out the variable name in the diff. 
Go to device and click on Config Compliance (screen shot below)
 
![image](https://github.com/user-attachments/assets/ba118eb7-5574-4778-bc29-a4457ca4681b)

However, if I go to scripts and choose the device and check “Commit changes” I am getting the expected result, the regex is being captured and removed from the config diff.
 
![image](https://github.com/user-attachments/assets/319a2b03-13ca-470b-a5a9-5c39d849797e)

thank you for looking into this issue.

**Comment by miaow2** [comment]
@jibz89 I think I fix this bug, please check the new release 2.8.0
