### ISSUE TITLE
Config Diff showing multiple empty lines as mismatched

### ISSUE THREAD

**Issue by Dz3015** [miaow2/netbox-config-diff#84]
**NetBox version**
v4.0.6

**Describe the bug**
On many devices I am showing large blocks of empty lines that are marked as diffed:

**To Reproduce**
1. Go to ConfigDiffScript
2. Click on 'Run script'
3. Then go to 'Config Compliances'
4. See results in diff

**Expected behavior**
Diff only for lines containing config

**Screenshots**
![image](https://github.com/user-attachments/assets/d8e23602-dc74-431d-9ac3-530ad13f9c7a)

**Additional context**
Filters are applied on the Platform settings

**Comment by chris240189** [comment]
that is expected behaviour in my book.
if you want to filter them from the diff, did you try to filter them with the exclude regex in the platform settings?

**Comment by Dz3015** [comment]
> that is expected behaviour in my book. if you want to filter them from the diff, did you try to filter them with the exclude regex in the platform settings?

Yes that is exactly what I did.  I have filtered these lines in the platform settings.  I would expect at that point they are ignored by the diff, not marked.

**Comment by miaow2** [comment]
Hi @Dz3015 thanks for opening the issue,

I added tweak before diff, that replaces long sequences of new lines with only one line, is his fine solution for you?

```python
>>> a = "a\n\n\n\n\n\n\n\n\n\nb\na\n\n\n\n\n\n\n\n\n\nb"
>>> re.sub("\n{3,}", "\n", a)
'a\nb\na\nb'
>>>
```

**Comment by miaow2** [comment]
@Dz3015 so lets try how it will work in your tasks, please update the plugin to the latest version 2.8.0

and feel free to open a new issue or reopen this, if you still have a problem with a lot of empty newlines
