### ISSUE TITLE
aruba_aoscx driver not working

### ISSUE THREAD

**Issue by Blusafur** [miaow2/netbox-config-diff#87]
**NetBox version**
v4.1.3

**Describe the bug**
I get an error "Driver(s) not supported: aruba_aoscx" when trying to configure a new configuration request

**To Reproduce**
1. Create a platform using the "aruba_aoscx" driver and "show run" for the command
2. Try to create a configuration request using that Aruba CX device and the platform you just created
3. Get the error "Driver(s) not supported: aruba_aoscx" under the Devices field in configuration request

**Expected behavior**
I expect the configuration request to be created and usable

**Screenshots**
![image](https://github.com/user-attachments/assets/a2a7d1fd-7cb9-4625-8595-f74c038bf75e)

**Additional context**
I just freshly installed this plugin and am trying to use it for the first time today
![image](https://github.com/user-attachments/assets/ded608e7-a03d-4b45-875f-1490583f9695)

**Comment by miaow2** [comment]
Hi @Blusafur thanks for opening the issue,

I am sorry, but the plugin does not support Aruba devices for configuration, because under the hood plugin uses [scrapli-cfg](https://github.com/scrapli/scrapli_cfg) lib, which supports only Arista, Cisco and Juniper devices.

**Comment by Blusafur** [comment]
You mention "Aruba AOSCX (aruba_aoscx)" at the bottom of the documentation page below so maybe that is why I am a little confused.
https://miaow2.github.io/netbox-config-diff/colliecting-diffs/

Is there any support for any of the platforms in the community package?
https://github.com/scrapli/scrapli_community

**Comment by miaow2** [comment]
> You mention "Aruba AOSCX (aruba_aoscx)" at the bottom of the documentation page below so maybe that is why I am a little confused.

this platform list is about supporting missing/extra command lines in diffs

> Is there any support for any of the platforms in the community package?

all platforms from scrapli community are supported

**Comment by Blusafur** [comment]
> > You mention "Aruba AOSCX (aruba_aoscx)" at the bottom of the documentation page below so maybe that is why I am a little confused.
> 
> this platform list is about supporting missing/extra command lines in diffs
> 
> > Is there any support for any of the platforms in the community package?
> 
> all platforms from scrapli community are supported

I'm still a little confused about your answer. You say aruba_aoscx is not supported, but scrapli community is supported which contains aruba_aoscx.

**Comment by miaow2** [comment]
plugin has two features:

1. rendering diff
2. configuring devices

plugin for `aruba_aoscx` supports only rendering diff option

**Comment by Blusafur** [comment]
Thank you. I understand now.
