### ISSUE TITLE
Documentation on how to trigger ConfigDiffScript programmatically

### ISSUE THREAD

**Issue by chris240189** [miaow2/netbox-config-diff#92]
How can I (if it isn't a hard limitation of netbox) invoke a configdiff script run from another custom script or from nb-shell?

I have a few custom scripts that import data into netbox (device interface configurations). Some imports are done through ansbile, some through a custom script.

Usually when I import data to a device in netbox or update the switch-config oxidized based netbox datasource, I have to manually run another ConfigDiffScript run or wait for the next scheduled run.

I wonder if I could trigger the generation of a new ConfigCompliance object programmatically, when I know I data has changed.

**Comment by miaow2** [comment]
Hi @chris240189, you can run script like this

```python
from django.utils.datastructures import MultiValueDict
from extras.models import Script
from utilities.request import NetBoxFakeRequest

script = Script.objects.get(name=self.script_name)
request = NetBoxFakeRequest(
    {
        "COOKIES": {},
        "FILES": MultiValueDict(),
        "GET": QueryDict(),
        "META": {
            "HTTP_HOST": "netbox",
            "REQUEST_METHOD": "POST",
        },
        "POST": QueryDict(),
        "path": <path to script like "/extras/scripts/{id}">,
        "user": job.user,
        "id": uuid.uuid4(),
    }
)

data = {
    "_commit": True,
    # here you add data for script
}
ScriptJob = import_string("extras.jobs.ScriptJob")
new_job = ScriptJob.enqueue(
    instance=script,
    user=request.user,
    schedule_at=data.pop("_schedule_at", None),
    interval=data.pop("_interval", None),
    data=data,
    request=request,
    job_timeout=script.python_class.job_timeout,
    commit=data.pop("_commit", None),
)
```

**Comment by chris240189** [comment]
thank you for supplying some code so quickly.
Right now I have two scripts that update data in netbox.

- I get new device configs from oxidized and put them into a netbox local datasource that I use a source to diff to though a scheduled netbox custom script.
- The second is a ansible playbook that fetches device interface configuration data from an external source.

I'll have a look how to integrate your snippet into my code.

**Comment by miaow2** [comment]
I think the best way is in the end to run `ConfigDiffScript ` script from API, it takes less code and is easy to support

**Comment by chris240189** [comment]
okay, I am trying to invoke it through the REST-API using ansible:

`- name: '{{ netbox_url }}/api/extras/scripts/1/'
  uri:
    url: '{{ netbox_url }}/api/extras/scripts/1/'
    method: POST
    body:
      data:
        data_source: 1
        devices: 934
      commit: true
    body_format: json
    headers:
      Authorization: 'Token {{ netbox_token }}'
      Content-Type: application/json
      Accept: 'application/json; indent=4'
  register: result`

the integer values are the netbox-ids of the data_source and device in question, however the script fails with 

"message": "An exception occurred: `KeyError: 'site'`\n```\nTraceback (most recent call last):\n  File \"/opt/netbox/netbox/extras/jobs.py\", line 45, in run_script\n    script.output = script.run(data, commit)\n  File \"/opt/netbox/netbox/scripts/config_diff.py\", line 12, in run\n    self.run_script(data)\n  File \"/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_diff/compliance/base.py\", line 68, in run_script\n    devices = self.validate_data(data)\n  File \"/opt/netbox/venv/lib/python3.10/site-packages/netbox_config_diff/compliance/base.py\", line 75, in validate_data\n    if not data[\"site\"] and not data[\"role\"] and not data[\"devices\"]:\nKeyError: 'site'\n\n```",

**Comment by miaow2** [comment]
in data define keys `site` and `role` with any number

in next release I will fix mandatory of this fields in validation

**Comment by chris240189** [comment]
that still doesn't work.
I believe netbox handles passed IDs weirdly and is interpreting them not automatically as object id (and doesn't convert them to an object).

See also:
https://github.com/netbox-community/netbox/discussions/16255

**Comment by miaow2** [comment]
yeah, I also can't run the script from the API, so try to run like in the code I provided,

feel free to ask any questions about this approach
